#!/usr/bin/env python3

import argparse
import json
import subprocess
import sys

from asset_runtime import (
    atomic_write_text,
    ensure_state_layout,
    get_host_context_targets,
    get_memory_mode,
    get_runtime_paths,
)


PATHS = get_runtime_paths()
BUILD_CODEX_MEMORY_SUMMARY = PATHS.repo_root / "scripts" / "build_codex_memory_summary.py"
MANAGED_START = "<!-- openrelix:shared-memory:start -->"
MANAGED_END = "<!-- openrelix:shared-memory:end -->"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Sync one bounded OpenRelix personal memory summary into enabled AI host contexts."
    )
    parser.add_argument("--print-json", action="store_true")
    return parser.parse_args()


def build_shared_summary():
    output_path = PATHS.runtime_dir / "shared-personal-memory-summary.md"
    cmd = [
        sys.executable,
        str(BUILD_CODEX_MEMORY_SUMMARY),
        "--memory-summary",
        str(output_path),
    ]
    subprocess.run(cmd, check=True)
    return output_path, output_path.read_text(encoding="utf-8")


def sync_codex_summary(summary_text):
    target = PATHS.codex_home / "memories" / "memory_summary.md"
    atomic_write_text(target, summary_text)
    return target


def clear_codex_summary():
    target = PATHS.codex_home / "memories" / "memory_summary.md"
    if target.is_symlink() or target.is_file():
        target.unlink()
        return {"host": "codex", "path": str(target), "status": "removed"}
    if target.exists():
        return {"host": "codex", "path": str(target), "status": "skipped", "detail": "not a file"}
    return {"host": "codex", "path": str(target), "status": "missing"}


def managed_claude_block(summary_text):
    body = summary_text.strip()
    return "\n".join(
        [
            MANAGED_START,
            "# OpenRelix Shared Personal Memory",
            "",
            "This block is generated by OpenRelix from the shared local personal-memory registry.",
            "Edit OpenRelix memory sources instead of editing this managed block by hand.",
            "",
            body,
            MANAGED_END,
            "",
        ]
    )


def replace_managed_block(existing_text, block_text):
    if MANAGED_START in existing_text and MANAGED_END in existing_text:
        before, _, tail = existing_text.partition(MANAGED_START)
        _, _, after = tail.partition(MANAGED_END)
        return before.rstrip() + "\n\n" + block_text.rstrip() + "\n\n" + after.lstrip()
    if existing_text.strip():
        return existing_text.rstrip() + "\n\n" + block_text
    return block_text


def strip_managed_block(existing_text):
    if MANAGED_START not in existing_text or MANAGED_END not in existing_text:
        return existing_text, False
    before, _, tail = existing_text.partition(MANAGED_START)
    _, _, after = tail.partition(MANAGED_END)
    updated = "\n\n".join(part.strip() for part in (before, after) if part.strip())
    return (updated + "\n" if updated else ""), True


def sync_claude_summary(summary_text):
    target = PATHS.claude_home / "CLAUDE.md"
    try:
        existing_text = target.read_text(encoding="utf-8")
    except (FileNotFoundError, OSError, UnicodeDecodeError):
        existing_text = ""
    atomic_write_text(target, replace_managed_block(existing_text, managed_claude_block(summary_text)))
    return target


def clear_claude_summary():
    target = PATHS.claude_home / "CLAUDE.md"
    try:
        existing_text = target.read_text(encoding="utf-8")
    except FileNotFoundError:
        return {"host": "claude", "path": str(target), "status": "missing"}
    except (OSError, UnicodeDecodeError) as exc:
        return {"host": "claude", "path": str(target), "status": "error", "detail": exc.__class__.__name__}

    updated, removed = strip_managed_block(existing_text)
    if not removed:
        return {"host": "claude", "path": str(target), "status": "kept", "detail": "no managed block"}
    if updated.strip():
        atomic_write_text(target, updated)
    else:
        target.unlink()
    return {"host": "claude", "path": str(target), "status": "removed"}


def main():
    args = parse_args()
    ensure_state_layout(PATHS)
    memory_mode = get_memory_mode(PATHS)
    targets = get_host_context_targets(PATHS) if memory_mode == "integrated" else []
    synced = []
    cleared = []

    summary_path = None
    summary_text = ""
    if targets:
        summary_path, summary_text = build_shared_summary()

    if "codex" in targets:
        synced.append({"host": "codex", "path": str(sync_codex_summary(summary_text))})
    else:
        cleared.append(clear_codex_summary())

    if "claude" in targets:
        synced.append({"host": "claude", "path": str(sync_claude_summary(summary_text))})
    else:
        cleared.append(clear_claude_summary())

    payload = {
        "ok": True,
        "memory_mode": memory_mode,
        "summary_path": str(summary_path) if summary_path else "",
        "targets": targets,
        "synced": synced,
        "cleared": cleared,
    }
    if args.print_json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
